name: "CI Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0"]
        rails: ["7.2", "8.0", "8.1"]
        include:
          - ruby: "4.0"
            rails: "main"

    env:
      RAILS_ENV: "test"
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
    - uses: "actions/checkout@v4"

    - name: "Install NodeJS"
      uses: "actions/setup-node@v4"
      with:
        node-version: "20.x"

    - name: "Install Ruby ${{ matrix.ruby }}"
      uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: "Run Setup"
      run: |
        bin/setup

    - name: "Run Tests"
      run: |
        bin/rake
