name: "CI Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4", "4.0"]
        rails: ["7.2", "8.0", "8.1"]
        include:
          - ruby: "4.0"
            rails: "main"

    env:
      RAILS_ENV: "test"
      RAILS_VERSION: "${{ matrix.rails }}"

    steps:
    - uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5" # v4.3.1

    - name: "Install NodeJS"
      uses: "actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f" # v6.3.0
      with:
        node-version: "20.x"

    - name: "Install Ruby ${{ matrix.ruby }}"
      uses: "ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64" # v1.299.0
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true

    - name: "Run Setup"
      run: |
        bin/setup

    - name: "Run Tests"
      run: |
        bin/rake
